name: Native GPU Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test-nvidia:
    uses: ./.github/workflows/nvidia-test.yaml
    with:
      runner_label: h100
      gpu_check_script: tools/check_nvidia_gpu.sh
